apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore2
  namespace: default
  description: The petstore API Test
  annotations:
    backstage.io/source-location: >-
      url:https://qa.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/module/code/orgs/default/projects/debaidptest/repos/test-united/files/main/~/
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  owner: team-c
  type: openapi
  lifecycle: experimental
  definition: random
